import './globals.css';
import { Inter } from 'next/font/google';
import Header from './components/Header';
import Footer from './components/Footer';
const inter = Inter({ subsets: ['latin'] });

export const metadata = {
  title: 'My first nextjs project',
  description: 'Generated by create next app, this is my first nextjs project',
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <div className="grid grid-rows-layout h-screen min-w-full">
          <Header />
          <main>{children}</main>
          <Footer />
        </div>
      </body>
    </html>
  );
}
